# Generated by Django 6.0.3 on 2026-06-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_ingredient_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.product')),
                ('dairy_free', models.BooleanField(default=False)),
                ('category', models.CharField(default='Food', max_length=50)),
            ],
            bases=('tasks.product',),
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('foodproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.foodproduct')),
                ('sweetness_level', models.CharField(default='Medium', max_length=50)),
            ],
            bases=('tasks.foodproduct',),
        ),
        migrations.CreateModel(
            name='GourmetIceCream',
            fields=[
                ('dessert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.dessert')),
                ('flavor', models.CharField(max_length=100)),
                ('scoop_size', models.CharField(default='Standard', max_length=50)),
            ],
            bases=('tasks.dessert',),
        ),
    ]
